# This is a basic workflow to help you get started with Actions

name: multi_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GITHUB }}
          submodules: true

      - name: Restore cached build directory
        uses: actions/cache@v3
        with:
          path: |
            vendor/Build/iOS_Device
            vendor/Build/iOS_Simulator
          key: iOS-build-${{ github.sha }}

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          unityVersion: 6000.0.28f1
          projectPath: vendor
          buildMethod: BuildScript.UniversaliOS
          customImage: 'unityci/editor:6000.0.29f1-ios-3.1'

      - name: Cache build directory
        uses: actions/cache@v3
        with:
          path: |
            vendor/Build/iOS_Device
            vendor/Build/iOS_Simulator
          key: iOS-build-${{ github.sha }}

  compile_project:
      runs-on: macOS-latest
      needs: build_project
      env:
        IOS_DEVICE_PROJECT_PATH: vendor/Build/iOS_Device
        IOS_SIMULATOR_PROJECT_PATH: vendor/Build/iOS_Simulator
        ARCHIVE_PATH: vendor/Build/archives
        DEVICE_ARCHIVE_PATH: vendor/Build/archives/iOS_Device.xcarchive
        SIMULATOR_ARCHIVE_PATH: vendor/Build/archives/iOS_Simulator.xcarchive
        XCFRAMEWORK_NAME: UnityFramework.xcframework
        XCFRAMEWORK_PATH: vendor/Build/archives/UnityFramework.xcframework
      steps:
          
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable

        - name: Install the Apple certificate and provisioning profile
          env:
            BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          run: |
            # create variables
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

            # import certificate and provisioning profile from secrets
            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
            echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

            # create temporary keychain
            security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

            # import certificate to keychain
            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH

        - name: Restore cached build directory
          uses: actions/cache@v3
          with:
            path: |
                vendor/Build/iOS_Device
                vendor/Build/iOS_Simulator
            key: iOS-build-${{ github.sha }}

        - name: Build UnityFramework for iOS Device
          run: |
            xcodebuild -project "${IOS_DEVICE_PROJECT_PATH}/Unity-iPhone.xcodeproj" \
            -scheme UnityFramework \
            -configuration Release \
            -sdk iphoneos \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES \
            -archivePath "${DEVICE_ARCHIVE_PATH}" \
            SKIP_INSTALL=NO \
            LLVM_LTO=YES \
            archive

        - name: Build UnityFramework for iOS Simulator
          run: |
            xcodebuild -project "${IOS_SIMULATOR_PROJECT_PATH}/Unity-iPhone.xcodeproj" \
            -scheme UnityFramework \
            -configuration Release \
            -sdk iphonesimulator \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES \
            -archivePath "${SIMULATOR_ARCHIVE_PATH}" \
            SKIP_INSTALL=NO \
            LLVM_LTO=YES \
            archive

        - name: Create XCFramework
          run: |
            xcodebuild -create-xcframework \
            -archive "${DEVICE_ARCHIVE_PATH}" -framework UnityFramework.framework \
            -archive "${SIMULATOR_ARCHIVE_PATH}" -framework UnityFramework.framework \
            -output "${XCFRAMEWORK_PATH}"

        - name: Code sign
          run: |
            cd vendor/Build/archives && \
            codesign --timestamp -s "Apple" "${XCFRAMEWORK_PATH}/UnityFramework.framework"
        
        - name: zip XCFramework
          run: |
            cd vendor/Build/archives && \
            zip -r -9 UnityFramework-iOS-Release.zip UnityFramework.xcframework && \
            mv -f UnityFramework-iOS-Release.zip ../UnityFramework-iOS-Release.zip
        
        - name: Verify XCFramework
          run: |
            ls -al "vendor/Build/UnityFramework-iOS-Release.zip"

