# This is a basic workflow to help you get started with Actions

name: multi_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
        tag_name:
          description: "The tag name for the release"
          required: true

env:
    IOS_DEVICE_PROJECT_PATH: vendor/Build/iOS_Device
    IOS_SIMULATOR_PROJECT_PATH: vendor/Build/iOS_Simulator

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_GITHUB }}
          submodules: recursive
          lfs: true

      - name: Unity Library Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor/Library
          key: iOS-Unity-Library

      - name: Unity Build Cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.IOS_DEVICE_PROJECT_PATH }}
            ${{ env.IOS_SIMULATOR_PROJECT_PATH }}
          key: iOS-Unity-Build

      - name: move Cache
        run: |
          mv vendor/Library target/project/Library
          mv vendor/Build/iOS_Device target/project/Build/iOS_Device
          mv vendor/Build/iOS_Simulator target/project/Build/iOS_Simulator

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
        #   unityVersion: 6000.0.28f1
          projectPath: target/project
          buildMethod: BuildScript.UniversaliOS
          customImage: 'unityci/editor:6000.0.29f1-ios-3.1'

      - name: Move Cache Back
        run: |
          mv target/project/Library vendor/Library
          mv target/project/Build/iOS_Device vendor/Build/iOS_Device
          mv target/project/Build/iOS_Simulator vendor/Build/iOS_Simulator

  compile_project:
    # 2024-12-01 macos-14 only has 7GB of memory while macos-13 has double
      runs-on: macos-latest
      needs: build_project
      env:
        ARCHIVE_PATH: vendor/Build/archives
        XCFRAMEWORK_NAME: UnityFramework.xcframework
        ARTIFACT_NAME: UnityFramework-iOS-Release.zip
      steps:
          
        - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: latest-stable

        - name: Install the Apple certificate and provisioning profile
          env:
            BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
            P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
            KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          run: |
            # create variables
            CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
            PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
            KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

            # import certificate and provisioning profile from secrets
            echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
            echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

            # create temporary keychain
            security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
            security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

            # import certificate to keychain
            security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
            security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
            security list-keychain -d user -s $KEYCHAIN_PATH

        - name: Unity Build Cache
          uses: actions/cache@v4
          with:
            path: |
                ${{ env.IOS_DEVICE_PROJECT_PATH }}
                ${{ env.IOS_SIMULATOR_PROJECT_PATH }}
            key: iOS-Unity-Build

        - name: Build UnityFramework for iOS Device
          run: |
            xcodebuild -project "${IOS_DEVICE_PROJECT_PATH}/Unity-iPhone.xcodeproj" \
            -scheme UnityFramework \
            -configuration Release \
            -sdk iphoneos \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES \
            -archivePath "${DEVICE_ARCHIVE_PATH}" \
            SKIP_INSTALL=NO \
            LLVM_LTO=YES \
            archive
          env:
            DEVICE_ARCHIVE_PATH: ${{ env.ARCHIVE_PATH }}/iOS_Device.xcarchive

        - name: Build UnityFramework for iOS Simulator
          run: |
            xcodebuild -project "${IOS_SIMULATOR_PROJECT_PATH}/Unity-iPhone.xcodeproj" \
            -scheme UnityFramework \
            -configuration Release \
            -sdk iphonesimulator \
            BUILD_LIBRARIES_FOR_DISTRIBUTION=YES \
            -archivePath "${SIMULATOR_ARCHIVE_PATH}" \
            SKIP_INSTALL=NO \
            LLVM_LTO=YES \
            archive
          env:
            SIMULATOR_ARCHIVE_PATH: ${{ env.ARCHIVE_PATH }}/iOS_Simulator.xcarchive

        - name: Create XCFramework
          run: |
            xcodebuild -create-xcframework \
            -archive "${DEVICE_ARCHIVE_PATH}" -framework UnityFramework.framework \
            -archive "${SIMULATOR_ARCHIVE_PATH}" -framework UnityFramework.framework \
            -output "${XCFRAMEWORK_PATH}"
          env:
            XCFRAMEWORK_PATH: ${{ env.ARCHIVE_PATH }}/${{ env.XCFRAMEWORK_NAME }}
            DEVICE_ARCHIVE_PATH: ${{ env.ARCHIVE_PATH }}/iOS_Device.xcarchive
            SIMULATOR_ARCHIVE_PATH: ${{ env.ARCHIVE_PATH }}/iOS_Simulator.xcarchive

        - name: Code sign
          run: |
            # Find available codesigning identities
            IDENTITY=$(security find-identity -v -p codesigning | grep -oE '\".*\"' | sed 's/"//g' | head -n 1)
            # Check if an identity is found
            if [ -z "$IDENTITY" ]; then
              echo "No valid code signing identity found."
              exit 1
            fi
            echo "Using identity: $IDENTITY"

            # Perform code signing
            cd $ARCHIVE_PATH && \
            codesign --timestamp -s "Apple" "$XCFRAMEWORK_NAME"
        
        - name: zip XCFramework
          run: |
            cd $ARCHIVE_PATH && \
            zip -r -9 $ARTIFACT_NAME $XCFRAMEWORK_NAME && \
            mv -f $ARTIFACT_NAME ../$ARTIFACT_NAME

        - name: Compute checksum
          id: compute_checksum
          run: |
              cd vendor/Build
              CHECKSUM=$(swift package compute-checksum $ARTIFACT_NAME)
              echo "checksum=$CHECKSUM" >> $GITHUB_OUTPUT

        - name: Create GitHub Release
          id: create_release
          uses: actions/github-script@v7
          with:
              github-token: ${{ secrets.PAT_GITHUB }}
              script: |
                const { data: release } = await github.rest.repos.createRelease({
                  owner: "TEAM-42KR",
                  repo: "MafiaUnity-Binary",
                  tag_name: "${{ github.event.inputs.tag_name }}",
                  name: "UnityFramework ${{ github.event.inputs.tag_name }}",
                  body: "### UnityFramework iOS Release\n- **Checksum**: ${{ steps.compute_checksum.outputs.checksum }}",
                  draft: true,
                  prerelease: true,
                });
                core.setOutput("release_id", release.id);
                core.setOutput("upload_url", release.upload_url);
    
        - name: Upload Release Asset
          id: upload_asset
          uses: actions/github-script@v7
          with:
              github-token: ${{ secrets.PAT_GITHUB }}

              script: |
                const fs = require('fs/promises');
                const path = "vendor/Build/${{ env.ARTIFACT_NAME }}";
                const { data: asset } = await github.rest.repos.uploadReleaseAsset({
                  owner: "TEAM-42KR",
                  repo: "MafiaUnity-Binary",
                  release_id: ${{ steps.create_release.outputs.release_id }},
                  name: "${{ env.ARTIFACT_NAME }}",
                  data: await fs.readFile(path),
                  headers: {
                    "content-type": "application/zip",
                    "content-length": (await fs.stat(path)).size,
                  },
                });
                core.setOutput("asset_id", asset.id);
    
        - name: Update Release with Asset ID
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.PAT_GITHUB }}
            script: |
                const release_id = ${{ steps.create_release.outputs.release_id }};
                const asset_id = ${{ steps.upload_asset.outputs.asset_id }};
                const checksum = "${{ steps.compute_checksum.outputs.checksum }}";
    
                await github.rest.repos.updateRelease({
                  owner: "TEAM-42KR",
                  repo: "MafiaUnity-Binary",
                  release_id: release_id,
                  draft : false,
                  body: `### UnityFramework iOS Release
                  - **Checksum**: ${checksum}
                  - **Asset ID**: ${asset_id}
                  - **Download**: https://api.github.com/repos/TEAM-42KR/MafiaUnity-Binary/releases/assets/${release_id}`,
                });
